name: Xiaoqing Liu's Group
description: none
url: http://xiaoqingliu.whu.edu.cn
baseurl: 
markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "deploy.sh"
