name: Xiaoqing Liu's Group
description: none
url: https://github.com/wsyxbcl/liu_lab
markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "deploy.sh"
  - "ghp_deploy.sh"
